In [2]:
import torch

In [ ]:
torch.__version__

'2.5.1+cu124'

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Fri Jan 31 03:32:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
a = torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [ ]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.7497, 0.5849],
        [0.1087, 0.5668]])

In [ ]:
torch.manual_seed(10)   # to get the same values always using the rand function
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [ ]:
torch.manual_seed(10)   # to get the same values always using the rand function
torch.rand(2,2)

tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]])

In [ ]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(4, 8)

tensor([4, 5, 6, 7])

In [ ]:
torch.arange(10, 20, 2)   # step 2

tensor([10, 12, 14, 16, 18])

In [ ]:
torch.linspace(0, 10, 20)  # generate 20 numbers between 0 to 10

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [ ]:
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [3]:
x = torch.Tensor([[1,2,3], [4,5,6]])

In [ ]:
torch.empty_like(x)

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [ ]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2139, 0.4118, 0.6938],
        [0.9693, 0.6178, 0.3304]])

In [5]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
x+2

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [6]:
x*2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [7]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [8]:
x**2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [9]:
c = torch.tensor([1, -2, 3, -4])

In [10]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [11]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [12]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [13]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [14]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [15]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [16]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

In [17]:
torch.sum(e)

tensor(55.)

In [18]:
torch.sum(e, dim=0)

tensor([17.,  5.,  9., 24.])

In [19]:
torch.sum(e, dim=1)

tensor([20., 14., 21.])

In [20]:
torch.mean(e, dim=1)

tensor([5.0000, 3.5000, 5.2500])

In [21]:
torch.mean(e)

tensor(4.5833)

In [22]:
torch.min(e)

tensor(0.)

In [23]:
torch.max(e)

tensor(9.)

In [24]:
torch.argmax(e)

tensor(0)

In [25]:
torch.argmin(e)

tensor(1)

In [29]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [30]:
f

tensor([[1, 9, 3],
        [2, 2, 0]])

In [31]:
g

tensor([[0, 5],
        [0, 7],
        [5, 9]])

In [32]:
torch.matmul(f,g)

tensor([[15, 95],
        [ 0, 24]])

In [33]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [34]:
vector1

tensor([1, 2])

In [35]:
vector2

tensor([3, 4])

In [36]:
torch.dot(vector1, vector2)

tensor(11)

In [37]:
f

tensor([[1, 9, 3],
        [2, 2, 0]])

In [38]:
torch.transpose(f, 0,1)

tensor([[1, 2],
        [9, 2],
        [3, 0]])

In [40]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [41]:
h

tensor([[9., 7., 0.],
        [6., 6., 7.],
        [1., 7., 5.]])

In [42]:
torch.inverse(h)

tensor([[ 0.0572,  0.1054, -0.1476],
        [ 0.0693, -0.1355,  0.1898],
        [-0.1084,  0.1687, -0.0361]])

In [43]:
torch.log(h)

tensor([[2.1972, 1.9459,   -inf],
        [1.7918, 1.7918, 1.9459],
        [0.0000, 1.9459, 1.6094]])

In [44]:
torch.exp(h)

tensor([[8.1031e+03, 1.0966e+03, 1.0000e+00],
        [4.0343e+02, 4.0343e+02, 1.0966e+03],
        [2.7183e+00, 1.0966e+03, 1.4841e+02]])

In [45]:
torch.softmax(h,0)

tensor([[9.5227e-01, 4.2232e-01, 8.0254e-04],
        [4.7411e-02, 1.5536e-01, 8.8009e-01],
        [3.1945e-04, 4.2232e-01, 1.1911e-01]])